export const siteConfig = {
  name: "Safetek",
  legalName: "Safetek Systems Ltd",
  url: "https://safetek.co.ke",
  ogImagePath: "/opengraph-image",
  twitter: "@safetek",
  locale: "en_KE",
  founded: "2018",
  email: "hello@safetek.co.ke",
  city: "Nairobi",
  country: "Kenya",
  founder: "Samuel Ndegwa",
  description:
    "Safetek is a software and AI company headquartered in Nairobi, Kenya. We build SaaS products for businesses across mobility, logistics, and healthcare — and partner with teams developing their own. Used by hundreds of operators every day.",
  shortDescription:
    "Software and AI for businesses across Africa. Built in Nairobi since 2018.",
  keywords: [
    "Safetek",
    "Safetek Systems",
    "Safetek Kenya",
    "software company Kenya",
    "software company Nairobi",
    "AI company Kenya",
    "AI consultancy Africa",
    "AI consultancy Nairobi",
    "SaaS development Kenya",
    "software development Nairobi",
    "custom software Kenya",
    "mobile app development Nairobi",
    "Android developer Kenya",
    "iOS developer Kenya",
    "React Native developers Kenya",
    "Next.js developers Africa",
    "AI engineering Kenya",
    "machine learning consultancy Africa",
    "LLM integration Kenya",
    "RAG implementation Africa",
    "prompt engineering Kenya",
    "AI chatbot developer Nairobi",
    "M-Pesa integration developer",
    "M-Pesa STK push integration",
    "Daraja API integration",
    "Safaricom Daraja developer",
    "M-Pesa SDK Kenya",
    "Co-op Bank API integration",
    "Cooperative Bank developer",
    "NCBA API integration",
    "NCBA Loop developer",
    "KCB API integration",
    "Equity Bank API",
    "fintech developer Kenya",
    "fintech consultancy Africa",
    "matatu management software",
    "matatu app developer",
    "matatu SACCO software",
    "transit management Kenya",
    "fleet management software Africa",
    "bus tracking software",
    "Komiut",
    "K-Parcel",
    "K~Parcel",
    "delivery tracking software Kenya",
    "logistics software Africa",
    "courier app Kenya",
    "last-mile delivery platform",
    "telemedicine platform Kenya",
    "telehealth software Africa",
    "Cuesports Africa",
    "snooker tournament platform",
    "pool tournament software",
    "billiards rankings Africa",
    "Saferoute",
    "routing engine Africa",
    "secure cloud Kenya",
    "cloud cost optimization Africa",
    "AWS consultancy Kenya",
    "Cloudflare developer Africa",
    "growth marketing Africa",
    "performance marketing Kenya",
    "digital agency Nairobi",
    "Nairobi tech company",
    "African SaaS",
  ] as string[],
};

export function absoluteUrl(path: string): string {
  if (path.startsWith("http")) return path;
  if (!path.startsWith("/")) return `${siteConfig.url}/${path}`;
  return `${siteConfig.url}${path}`;
}
